[2023-09-26 21:13:43,368] INFO _log() L187  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.17.86.197:5000 - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:13:43,368] INFO _log() L187  [33mPress CTRL+C to quit[0m - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:14:23,772] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:14:23] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:14:23,911] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:14:23] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:14:24,041] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:14:24] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:14:24,268] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:14:24] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:14:24,659] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:14:24] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:14:24,675] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:14:24] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:14:30,238] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:14:30] "DELETE /doc?id=1 HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:14:36,107] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:14:36] "DELETE /doc?id=2 HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:14:39,320] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:14:39] "DELETE /doc?id=3 HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:14:42,609] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:14:42] "DELETE /doc?id=4 HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:14:46,121] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:14:46] "DELETE /doc?id=5 HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:14:48,915] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:14:48] "DELETE /doc?id=6 HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:14:53,312] WARNING del_doc() L202  Erro ao deletar doc #'7', Doc não encontrado na base :/ - call_trace=C:\Users\lucas\Documents\GitHub\MVP_Lucas_Loureiro_PUC-Rio_-_Conversao_Moeda\meu_app_api\app.py L202 
[2023-09-26 21:14:53,314] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:14:53] "[33mDELETE /doc?id=7 HTTP/1.1[0m" 404 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:15:06,556] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:15:06] "GET /docs HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:18:59,408] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:18:59] "GET /docs HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:22:16,512] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:22:16] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:22:16,564] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:22:16] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:22:16,758] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:22:16] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:22:17,003] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:22:17] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:22:17,009] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:22:17] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:22:19,470] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:22:19] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:22:19,549] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:22:19] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:22:19,712] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:22:19] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:22:19,857] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:22:19] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:22:20,307] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:22:20] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:22:34,284] WARNING get_doc() L146  Erro ao buscar doc 'AG32234', Doc não encontrado na base :/ - call_trace=C:\Users\lucas\Documents\GitHub\MVP_Lucas_Loureiro_PUC-Rio_-_Conversao_Moeda\meu_app_api\app.py L146 
[2023-09-26 21:22:34,287] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:22:34] "[33mGET /doc?doc_num=AG32234 HTTP/1.1[0m" 404 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:22:43,436] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:22:43] "POST /doc HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:23:02,423] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:23:02] "DELETE /doc?id=1 HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:23:24,689] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:23:24] "PUT /doc HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:23:41,933] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:23:41] "GET /doc_id?id=1 HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:23:48,811] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:23:48] "GET /docs HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:24:24,871] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:24:24] "POST /doc HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:25:57,788] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:25:57] "OPTIONS /doc?id=1 HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:25:57,909] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:25:57] "DELETE /doc?id=1 HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:26:16,811] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:26:16] "GET /docs HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:32:54,539] INFO _log() L187  127.0.0.1 - - [26/Sep/2023 21:32:54] "GET /docs HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-26 21:32:58,323] WARNING del_doc() L202  Erro ao deletar doc #'1', Doc não encontrado na base :/ - call_trace=C:\Users\lucas\Documents\GitHub\MVP_Lucas_Loureiro_PUC-Rio_-_Conversao_Moeda\meu_app_api\app.py L202 
